language: generic

go:
  - 1.12.x

os: linux
dist: bionic

services:
  - docker

before_script:
  - ./ci/download_cli.sh

script:
  - . ./ci/build.sh

git:
  clone: false

install:
  - git clone https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
  - cd $TRAVIS_REPO_SLUG
  - git status -sb
  - git checkout $TRAVIS_COMMIT

# note before_deploy will run before each deploy provider
before_deploy:
  - . ./ci/release.sh

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file: ci/release/*
  file_glob: true
  on:
    tags: true
    repo: appsody/stacks
    branch: master
