language: generic

go:
  - 1.12.x

os: linux
dist: bionic

env:
  - GITHUB_READ_TOKEN: "05a26637e299a0d3481c9f9c62c8d5a373c74af9"

services:
  - docker

# Delete git repo setup from travis
# and replace with git clone to master.
# reset hard to $TRAVIS_COMMIT
install:
  - . ./ci/git_setup.sh

before_script:
  - ./ci/download_cli.sh

script:
  - . ./ci/build.sh

# note before_deploy will run before each deploy provider
before_deploy:
  - . ./ci/release.sh

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file: ci/release/*
  file_glob: true
  on:
    tags: true
    repo: appsody/stacks
    branch: master
